/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.testdemo

import java.time.LocalDateTime
import java.util.*

fun main(args: Array<String>) {
    val db = Database();
    val blog = Blog(db);

    val post = Post("My post", LocalDateTime.now())
}
