/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.testdemo

import java.time.LocalDateTime

class Blog(val db: Database) {

    fun addPost(post: Post, author: Author) {
        val email = author.email;
        val name = author.name;
        val body = post.body;
        val date = post.date;

        db.insertPost(email.toEmail(), name, body, date);
    }

    fun getPost(id: Int): Post {
        return Post(
                body = "My Post",
                date = LocalDateTime.now()
        )
    }


}
