/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.testdemo

import java.lang.Exception
import java.time.LocalDateTime

class Database {

    fun insertPost(email: String, name: String, body: String, date: LocalDateTime) {
        execute(("INSERT INTO `posts` (`email`,`name`,`body`,`date`) VALUES ('$email', '$name', '$body', '$date');"))
    }

    private fun execute(sql: String) {
        println("Executing: $sql");
    }

    fun wipe() {
        throw Exception("Boom!")
    }

}
