/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.testdemo

data class Email(val username: String, val domain: String) {

    fun isValid(): Boolean {
        return username.isNotEmpty() && domain.isNotEmpty()
    }

    fun toEmail(): String {
        return "$username@$domain"
    }


}
