/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.testdemo

import java.time.LocalDateTime

data class Post(val body: String, val date: LocalDateTime) {


}
